version: 0.2

phases:
  pre_build:
    commands:
      - echo Install packages...
      - npm install
  build:
    commands:
      - echo Create build...
      - npm run build
  post_build:
    commands:
      - echo Removing unnecessary files...
      - rm -rf node_modules/
      - echo Copying 'Templates' folder to 'dist'...
      - cp -R src/template dist/

artifacts:
  name: MyArtifact
  files:
    - package.json
    - package-lock.json
    - "dist/**/*"
  artifactType: zip
