const { Schema, model } = require("mongoose");

export const CustomerSchema = Schema({
  carrier: { type: String },
  policityType: { type: String },
  monthly: { type: String },
  faceAmount: { type: String },
  firstName: { type: String },
  middleName: { type: String },
  lastName: { type: String },
  address: { type: String },
  addressLine2: { type: String },
  city: { type: String },
  state: { type: String },
  zipCode: { type: String },
  phone: { type: String },
  phoneType: { type: String },
  email: { type: String },
  maritalStatus: { type: String },
  dateBirth: { type: Date },
  ss: { type: String },
  countryBirth: { type: Date },
  cityBirth: { type: Date },
  greenCard: { type: String },
  driversLicense: { type: String },
  expiration: { type: Date },
  stateGreenCard: { type: String },
  gender: { type: String },
  weight: { type: String },
  height: { type: String },
  employerName: { type: String },
  occupation: { type: String },
  timeEmployed: { type: String },
  annualIncome: { type: String },
  householdIncome: { type: String },
  householdNetWorth: { type: String },
});
